# Generated by Django 5.2.14 on 2026-07-21 13:03

import django.core.serializers.json
import django.db.models.deletion
import nautobot.core.models.fields
import nautobot.extras.models.mixins
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0142_remove_scheduledjob_approval_required'),
        ('nautobot_intent_catalog', '0013_analysis_provenance_and_generic_endpoint_policy'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrainDumpDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('_custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('authorship', models.CharField(max_length=32)),
                ('tags', nautobot.core.models.fields.TagsField(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'Braindump document',
                'verbose_name_plural': 'Braindump documents',
                'ordering': ('-last_updated', 'title'),
            },
            bases=(nautobot.extras.models.mixins.DataComplianceModelMixin, nautobot.extras.models.mixins.DynamicGroupMixin, nautobot.extras.models.mixins.NotesMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AlignmentReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('_custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('summary', models.TextField()),
                ('tags', nautobot.core.models.fields.TagsField(through='extras.TaggedItem', to='extras.Tag')),
                ('braindump', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alignment_review', to='nautobot_intent_catalog.braindumpdocument')),
            ],
            options={
                'verbose_name': 'Alignment review',
                'verbose_name_plural': 'Alignment reviews',
            },
            bases=(nautobot.extras.models.mixins.DataComplianceModelMixin, nautobot.extras.models.mixins.DynamicGroupMixin, nautobot.extras.models.mixins.NotesMixin, models.Model),
        ),
    ]
