# Generated by Django 5.2.14 on 2026-07-25, hand-reviewed for VM Phase 3.
#
# Adds the final DesiredComputePlatform/DesiredComputeInstance models and DesiredEndpoint.mac_address,
# then asserts no legacy DesiredNode.realized_vm link survives before dropping it in the same
# coordinated breaking migration. See devdocs/big/vm/p3/plan.md Section 5.10 and Step 2/8.

import uuid

import django.core.serializers.json
import django.db.models.deletion
import django.db.models.expressions
import django.db.models.fields.json
import django.db.models.functions.comparison
import nautobot.core.models.fields
import nautobot.extras.models.mixins
from django.db import migrations, models


def assert_no_legacy_realized_vm(apps, schema_editor):
    """Refuse to drop `DesiredNode.realized_vm(+_source)` while any row still uses it.

    This is the in-transaction repeat of the pre-maintenance-window assertion described in
    plan Section 5.10/7 Step 8: the coordinated cutover only proceeds when the legacy link is
    provably unused, never by discarding live data.
    """

    DesiredNode = apps.get_model("nautobot_intent_catalog", "DesiredNode")
    non_null_count = DesiredNode.objects.filter(realized_vm__isnull=False).count()
    if non_null_count:
        raise RuntimeError(
            "Refusing to drop DesiredNode.realized_vm: "
            f"{non_null_count} row(s) still have a non-null legacy realized_vm link. "
            "Resolve or intentionally migrate this data with an explicit reviewed migration "
            "before retrying 0015."
        )


class Migration(migrations.Migration):

    dependencies = [
        ("extras", "0142_remove_scheduledjob_approval_required"),
        ("ipam", "0055_rename_ipaddress_ip_version_host_mask_length_ipam_ipaddr_ip_vers_d82ba5_idx_and_more"),
        ("nautobot_intent_catalog", "0014_braindump_exchange_diary"),
        ("virtualization", "0030_alter_virtualmachine_local_config_context_data_owner_content_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DesiredComputeInstance",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                ("_custom_field_data", models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ("instance_kind", models.CharField(max_length=32)),
                ("desired_power_state", models.CharField(default="running", max_length=16)),
                ("vcpus", models.PositiveIntegerField()),
                ("memory_mb", models.PositiveIntegerField()),
                ("root_disk_gb", models.PositiveIntegerField()),
                ("config_schema_version", models.CharField(default="v1", editable=False, max_length=16)),
                ("config", models.JSONField(blank=True, default=dict)),
                ("realized_vm_source", models.CharField(blank=True, editable=False, max_length=16, null=True)),
            ],
            options={
                "verbose_name": "desired compute instance",
                "verbose_name_plural": "desired compute instances",
                "ordering": ("desired_node__name",),
            },
            bases=(nautobot.extras.models.mixins.DataComplianceModelMixin, nautobot.extras.models.mixins.DynamicGroupMixin, nautobot.extras.models.mixins.NotesMixin, models.Model),
        ),
        migrations.CreateModel(
            name="DesiredComputePlatform",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                ("_custom_field_data", models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("provider_type", models.CharField(default="proxmox", max_length=32)),
                ("lifecycle", models.CharField(default="active", max_length=64)),
                ("config_schema_version", models.CharField(default="v1", editable=False, max_length=16)),
                ("config", models.JSONField(blank=True, default=dict)),
                ("realized_cluster_source", models.CharField(blank=True, editable=False, max_length=16, null=True)),
            ],
            options={
                "verbose_name": "desired compute platform",
                "verbose_name_plural": "desired compute platforms",
                "ordering": ("name",),
            },
            bases=(nautobot.extras.models.mixins.DataComplianceModelMixin, nautobot.extras.models.mixins.DynamicGroupMixin, nautobot.extras.models.mixins.NotesMixin, models.Model),
        ),
        migrations.RunPython(assert_no_legacy_realized_vm, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="desirednode",
            name="realized_vm",
        ),
        migrations.RemoveField(
            model_name="desirednode",
            name="realized_vm_source",
        ),
        migrations.AddField(
            model_name="desiredendpoint",
            name="mac_address",
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
        migrations.AddConstraint(
            model_name="desiredendpoint",
            constraint=models.UniqueConstraint(condition=models.Q(("mac_address__isnull", False)), fields=("mac_address",), name="nic_unique_desired_mac_address"),
        ),
        migrations.AddField(
            model_name="desiredcomputeinstance",
            name="desired_node",
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="desired_compute_instance", to="nautobot_intent_catalog.desirednode"),
        ),
        migrations.AddField(
            model_name="desiredcomputeinstance",
            name="realized_vm",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="intent_catalog_desired_compute_instances", to="virtualization.virtualmachine"),
        ),
        migrations.AddField(
            model_name="desiredcomputeinstance",
            name="tags",
            field=nautobot.core.models.fields.TagsField(through="extras.TaggedItem", to="extras.Tag"),
        ),
        migrations.AddField(
            model_name="desiredcomputeplatform",
            name="control_node",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="controlled_compute_platforms", to="nautobot_intent_catalog.desirednode"),
        ),
        migrations.AddField(
            model_name="desiredcomputeplatform",
            name="realized_cluster",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="intent_catalog_desired_compute_platforms", to="virtualization.cluster"),
        ),
        migrations.AddField(
            model_name="desiredcomputeplatform",
            name="tags",
            field=nautobot.core.models.fields.TagsField(through="extras.TaggedItem", to="extras.Tag"),
        ),
        migrations.AddField(
            model_name="desiredcomputeinstance",
            name="platform",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="desired_compute_instances", to="nautobot_intent_catalog.desiredcomputeplatform"),
        ),
        migrations.AddConstraint(
            model_name="desiredcomputeplatform",
            constraint=models.CheckConstraint(condition=models.Q(("provider_type", "proxmox")), name="dcp_provider_type_proxmox"),
        ),
        migrations.AddConstraint(
            model_name="desiredcomputeplatform",
            constraint=models.CheckConstraint(condition=models.Q(("config_schema_version", "v1")), name="dcp_config_schema_v1"),
        ),
        migrations.AddConstraint(
            model_name="desiredcomputeplatform",
            constraint=models.CheckConstraint(condition=django.db.models.expressions.RawSQL("jsonb_typeof(config) = 'object'", (), output_field=models.BooleanField()), name="dcp_config_object"),
        ),
        migrations.AddConstraint(
            model_name="desiredcomputeinstance",
            constraint=models.CheckConstraint(condition=models.Q(("vcpus__gte", 1), ("vcpus__lte", 8192)), name="dci_vcpus_bounds"),
        ),
        migrations.AddConstraint(
            model_name="desiredcomputeinstance",
            constraint=models.CheckConstraint(condition=models.Q(("memory_mb__gte", 16), ("memory_mb__lte", 2147483647)), name="dci_memory_mb_bounds"),
        ),
        migrations.AddConstraint(
            model_name="desiredcomputeinstance",
            constraint=models.CheckConstraint(condition=models.Q(("root_disk_gb__gte", 1), ("root_disk_gb__lte", 2147483647)), name="dci_root_disk_gb_bounds"),
        ),
        migrations.AddConstraint(
            model_name="desiredcomputeinstance",
            constraint=models.CheckConstraint(condition=models.Q(("config_schema_version", "v1")), name="dci_config_schema_v1"),
        ),
        migrations.AddConstraint(
            model_name="desiredcomputeinstance",
            constraint=models.CheckConstraint(condition=django.db.models.expressions.RawSQL("jsonb_typeof(config) = 'object'", (), output_field=models.BooleanField()), name="dci_config_object"),
        ),
        migrations.AddConstraint(
            model_name="desiredcomputeinstance",
            constraint=models.UniqueConstraint(models.F("platform"), django.db.models.functions.comparison.Cast(django.db.models.fields.json.KeyTextTransform("vmid", "config"), output_field=models.BigIntegerField()), condition=models.Q(("config__has_key", "vmid")), name="dci_unique_platform_vmid"),
        ),
    ]
