# Generated by Django 5.2.14 on 2026-07-25, hand-reviewed for remove_unused_surfaces Phase 3.
#
# Drops the four dashboard-derived reconciliation cache fields from DesiredNode/DesiredService.
# This is a coordinated breaking deletion: no replacement table, JSON blob, or data migration
# translates the discarded values. See devdocs/big/remove_unused_surfaces/p3/plan.md Section 4.1.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nautobot_intent_catalog', '0015_compute_platform_instance_and_endpoint_mac'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desirednode',
            name='reconciliation_checked_at',
        ),
        migrations.RemoveField(
            model_name='desirednode',
            name='reconciliation_status',
        ),
        migrations.RemoveField(
            model_name='desiredservice',
            name='reconciliation_checked_at',
        ),
        migrations.RemoveField(
            model_name='desiredservice',
            name='reconciliation_status',
        ),
    ]
