# Generated by Django 4.2 on 2026-07-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nautobot_intent_catalog", "0017_merge_20260729_1945"),
    ]

    operations = [
        migrations.AddField(
            model_name="braindumpdocument",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("superseded", "Superseded")],
                default="active",
                max_length=16,
            ),
        ),
    ]
