# Generated by Django 5.2.14 on 2026-07-31 16:56

import django.core.serializers.json
import django.db.models.deletion
import nautobot.core.models.fields
import nautobot.extras.models.mixins
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0142_remove_scheduledjob_approval_required'),
        ('nautobot_intent_catalog', '0024_remove_desiredservice_backstage_identity'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesiredServiceBinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('_custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('binding_name', models.SlugField(max_length=255)),
                ('consumer_placement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_bindings', to='nautobot_intent_catalog.desiredserviceplacement')),
                ('provider_service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inbound_bindings', to='nautobot_intent_catalog.desiredservice')),
                ('tags', nautobot.core.models.fields.TagsField(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'desired service binding',
                'verbose_name_plural': 'desired service bindings',
                'ordering': ('consumer_placement__instance_name', 'binding_name'),
                'constraints': [models.UniqueConstraint(fields=('consumer_placement', 'binding_name'), name='nic_unique_binding_per_placement')],
            },
            bases=(nautobot.extras.models.mixins.DataComplianceModelMixin, nautobot.extras.models.mixins.DynamicGroupMixin, nautobot.extras.models.mixins.NotesMixin, models.Model),
        ),
    ]
