# Generated by Django 4.2 on 2026-08-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nautobot_intent_catalog", "0025_desiredservicebinding"),
    ]

    operations = [
        migrations.AddField(
            model_name="braindumpdocument",
            name="completion_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="braindumpdocument",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("superseded", "Superseded"), ("completed", "Completed")],
                default="active",
                max_length=16,
            ),
        ),
    ]
