# Generated by Django 5.2.14 on 2026-08-01 12:02

import django.core.serializers.json
import django.db.models.deletion
import nautobot.core.models.fields
import nautobot.extras.models.mixins
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0142_remove_scheduledjob_approval_required'),
        ('nautobot_intent_catalog', '0026_braindumpdocument_completed_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesiredWorkspace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('_custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('lifecycle', models.CharField(default='proposed', max_length=64)),
                ('source_remote_url', models.CharField(max_length=255)),
                ('expected_path', models.CharField(max_length=255)),
                ('desired_presence', models.CharField(default='present', max_length=16)),
                ('desired_node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='desired_workspaces', to='nautobot_intent_catalog.desirednode')),
                ('tags', nautobot.core.models.fields.TagsField(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'desired workspace',
                'verbose_name_plural': 'desired workspaces',
                'ordering': ('name',),
            },
            bases=(nautobot.extras.models.mixins.DataComplianceModelMixin, nautobot.extras.models.mixins.DynamicGroupMixin, nautobot.extras.models.mixins.NotesMixin, models.Model),
        ),
    ]
